networks:
  photopro.net:
    driver: bridge

services:
  web.photopro:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./web/photo-pro-backoffice:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    networks:
      - photopro.net
    depends_on:
      - app-gateway-gestion

  web.frontoffice:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./web/photo-pro-frontoffice:/app
      - /app/node_modules
    command: sh -c "npm install && npm run build && node .output/server/index.mjs"
    ports:
      - "3000:3000"
    networks:
      - photopro.net
    depends_on:
      - photopro-gallery.db
      - photopro-photo.db
      - app-auth
      - seaweed-s3
    environment:
      - HOST=0.0.0.0
      - PORT=3000

      # ✅ DB Gallery
      - NUXT_DB_HOST=photopro-gallery.db
      - NUXT_DB_PORT=5432
      - NUXT_DB_USER=${GALLERY_DB_USER}
      - NUXT_DB_PASSWORD=${GALLERY_DB_PASSWORD}
      - NUXT_DB_NAME=${GALLERY_DB_NAME}

      # ✅ DB Photo
      - NUXT_PHOTO_DB_HOST=photopro-photo.db
      - NUXT_PHOTO_DB_PORT=5432
      - NUXT_PHOTO_DB_USER=${PHOTO_DB_USER}
      - NUXT_PHOTO_DB_PASSWORD=${PHOTO_DB_PASSWORD}
      - NUXT_PHOTO_DB_NAME=${PHOTO_DB_NAME}

      # ✅ S3 (fix)
      - NUXT_PUBLIC_S3_ENDPOINT=http://localhost:8888

  app-gateway-gestion:
    build:
      context: build
      dockerfile: 8.5-cli.Dockerfile
    volumes:
      - ./api/gateway/:/var/php
    working_dir: /var/php
    ports:
      - "6080:80"
    networks:
      - photopro.net
    depends_on:
      - rabbitmq
      - seaweed-s3
      - mailer
      - app-auth
      - app-gallery
      - app-photo
    environment:
      - AUTH_API_URL=${AUTH_API_URL}
      - GALLERY_API_URL=${GALLERY_API_URL}
      - PHOTO_API_URL=${PHOTO_API_URL}
      - JWT_SECRET=${JWT_SECRET}
    command: sh -c "COMPOSER_PROCESS_TIMEOUT=1800 composer install --prefer-dist --no-interaction --no-progress && php -S 0.0.0.0:80 -t /var/php/public"

  app-gateway-front:
    build:
      context: build
      dockerfile: 8.5-cli.Dockerfile
    volumes:
      - ./api/gateway-front/:/var/php
    working_dir: /var/php
    ports:
      - "6083:80"
    networks:
      - photopro.net
    depends_on:
      - rabbitmq
      - seaweed-s3
      - mailer
      - app-auth
      - app-gallery
      - app-photo
    environment:
      - AUTH_API_URL=${AUTH_API_URL}
      - GALLERY_API_URL=${GALLERY_API_URL}
      - PHOTO_API_URL=${PHOTO_API_URL}
      - JWT_SECRET=${JWT_SECRET}
    command: sh -c "COMPOSER_PROCESS_TIMEOUT=1800 composer install --prefer-dist --no-interaction --no-progress && php -S 0.0.0.0:80 -t /var/php/public"

  # ── Auth ──────────────────────────────────────────────────────────────────
  app-auth:
    build:
      context: build
      dockerfile: 8.5-cli.Dockerfile
    volumes:
      - ./api/app-auth/:/var/php
    working_dir: /var/php
    networks:
      - photopro.net
    depends_on:
      - photopro-auth.db
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  photopro-auth.db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    networks:
      - photopro.net
    volumes:
      - photopro_auth_data:/var/lib/postgresql/data
      - ./sql/auth/01_photopro_auth.schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/auth/02_photopro_auth.data.sql:/docker-entrypoint-initdb.d/02_data.sql

  # ── Gallery ───────────────────────────────────────────────────────────────
  app-gallery:
    build:
      context: build
      dockerfile: 8.5-cli.Dockerfile
    ports:
      - "6081:80"
    volumes:
      - ./api/app-gallery/:/var/php
    working_dir: /var/php
    networks:
      - photopro.net
    depends_on:
      - photopro-gallery.db
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  photopro-gallery.db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${GALLERY_DB_USER}
      POSTGRES_PASSWORD: ${GALLERY_DB_PASSWORD}
      POSTGRES_DB: ${GALLERY_DB_NAME}
    networks:
      - photopro.net
    volumes:
      - photopro_gallery_data:/var/lib/postgresql/data
      - ./sql/gallery/01_photopro_gallery.schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/gallery/02_photopro_gallery.data.sql:/docker-entrypoint-initdb.d/02_data.sql

  # ── Photo ─────────────────────────────────────────────────────────────────
  app-photo:
    build:
      context: build
      dockerfile: 8.5-cli.Dockerfile
    volumes:
      - ./api/app-photo:/var/php
      - ./seed:/var/seed
    working_dir: /var/php
    ports:
      - "6082:80"
    networks:
      - photopro.net
    depends_on:
      - photopro-photo.db
      - seaweed-s3
    command: sh -c "composer install && php -S 0.0.0.0:80 -t public"

  photopro-photo.db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PHOTO_DB_USER}
      POSTGRES_PASSWORD: ${PHOTO_DB_PASSWORD}
      POSTGRES_DB: ${PHOTO_DB_NAME}
    networks:
      - photopro.net
    volumes:
      - photopro_photo_data:/var/lib/postgresql/data # ✅ AJOUT
      - ./sql/photo/01_photopro_photo.schema.sql:/docker-entrypoint-initdb.d/05.schema.sql
      - ./sql/photo/02_photopro_photo.data.sql:/docker-entrypoint-initdb.d/06.data.sql

  # ── SeaweedFS ─────────────────────────────────────────────────────────────
  seaweed-master:
    image: chrislusf/seaweedfs:latest
    command: "master -ip=seaweed-master -ip.bind=0.0.0.0"
    ports:
      - "9333:9333"
    networks:
      - photopro.net

  seaweed-volume:
    image: chrislusf/seaweedfs:latest
    command: 'volume -ip=seaweed-volume -master="seaweed-master:9333" -ip.bind=0.0.0.0 -port=8082'
    ports:
      - "8082:8082"
    depends_on:
      - seaweed-master
    networks:
      - photopro.net

  seaweed-filer:
    image: chrislusf/seaweedfs:latest
    command: 'filer -ip=seaweed-filer -master="seaweed-master:9333" -ip.bind=0.0.0.0'
    ports:
      - "8888:8888"
    depends_on:
      - seaweed-master
      - seaweed-volume
    networks:
      - photopro.net

  seaweed-s3:
    image: chrislusf/seaweedfs:latest
    command: 's3 -filer="seaweed-filer:8888" -ip.bind=0.0.0.0 -config=/etc/seaweedfs/s3.json'
    ports:
      - "8333:8333"
    depends_on:
      - seaweed-filer
    networks:
      - photopro.net
    environment:
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
    volumes:
      - ./S3/s3.json:/etc/seaweedfs/s3.json

  # ── Adminer ────────────────────────────────────────────────────────────────
  adminer:
    image: adminer:latest
    ports:
      - "8081:8081"
    networks:
      - photopro.net
    depends_on:
      - photopro-auth.db
      - photopro-gallery.db
      - photopro-photo.db
    command: php -S 0.0.0.0:8081 -t /var/www/html

  # ── Broker ────────────────────────────────────────────────────────────────
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - photopro.net

  # ── Mailer ────────────────────────────────────────────────────────────────
  mailer:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - photopro.net

volumes:
  photopro_auth_data:
  photopro_gallery_data:
  photopro_photo_data:
